[package]
name = "pruner-nvim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = {version = "0.5", features = ["neovim-0-10"]}
anyhow = "1.0"
once_cell = "1.19.0"




